### ISSUE TITLE
what is the importance of global phase ? How its effect a unit vector if we see it on a bloch sphere? what is the meaning of 'up to global phase' in exc 4.3?

### ISSUE THREAD

**Issue by vardhannegi** [rehaanahmad2013/NielsenChuang-QuantumComputingSolutions#1]

**Comment by rehaanahmad2013** [comment]
I think this link does a good job explaining: https://quantumcomputing.stackexchange.com/questions/5125/what-is-the-difference-between-a-relative-phase-and-a-global-phase-in-particula

A global phase does not affect a qubit's bloch sphere representation. If we have a qubit "v", a global phase means multiplying by some complex number with magnitude 1. The reason this is not important is, if you calculate the probability of the qubit being 0 or 1, these values stay exactly the same regardless of the global phase.
